### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by LiNCH35** [ilovepdf/iloveimg-php#3]
I got this message:

    Exception: SSL certificate problem: certificate has expired in /app/vendor/ilovepdf/iloveimg-php/src/Request/Request.php:399
    Stack trace:
      /app/vendor/ilovepdf/iloveimg-php/src/Request/Request.php(156): Iloveimg\Request\Request::send('GET', 'https://api.ilo...',         'v=php.1.0.2', Array, NULL, NULL)
    #1 /app/vendor/ilovepdf/iloveimg-php/src/Iloveimg.php(183): Iloveimg\Request\Request::get('https://api.ilo...', Array,     'v=php.1.0.2')
    #2 /app/vendor/ilovepdf/iloveimg-php/src/ImageTask.php(74): Iloveimg\Iloveimg->sendRequest('get', 'start/resizeima...', 'v=php.1.0.2')
    #3 /app/vendor/ilovepdf/iloveimg-php/src/ImageTask.php(66): Iloveimg\ImageTask->start()
    #4 /app/vendor/ilovepdf/iloveimg-php/src/ResizeImageTask.php(56): Iloveimg\ImageTask->__construct('project_public_...', 'secret_key_4537...', true)
    #5 /app/vendor/ilovepdf/iloveimg-php/src/Iloveimg.php(221): Iloveimg\ResizeImageTask->__construct('project_public_...', 'secret_key_4537...', true)
    #6 /app/common/useCases/Image/ImageResizeService.php(148): Iloveimg\Iloveimg->newTask('resize')

On `app/vendor/ilovepdf/iloveimg-php/src/Request/Request.php(397)` is written next:

    if(strpos($error,'SSL certificate problem')){
        throw new \Exception($error.' Try using  method verifySsl to false: "$iloveimg->verifySsl(false)"');
    }

But this exception is not catched

I add

    $iloveimg->verifySsl(false)

to my code, and it helped

**Comment by marcogrossisas** [comment]
Thanks for reporting: one certificate was not updated in one of the servers. Fixed.
